version: '3.7'
services:

    zandstra-php-fpm:
        image: ${REGISTRY}/${PHP_FPM_CONTAINER_NAME}:${IMAGE_TAG}
        volumes:
            - .:/app

    zandstra-php-cli:
        image: ${REGISTRY}/${PHP_CLI_CONTAINER_NAME}:${IMAGE_TAG}
        volumes:
            - .:/app

    zandstra-nginx:
        image: ${REGISTRY}/${NGINX_CONTAINER_NAME}:${IMAGE_TAG}
        ports:
            - ${APP_WEB_PORT}:80
        volumes:
            - .:/app
